Blood-Bank-Management-System/availability/urls.py
from django.urls import path
from . import views

app_name = 'availability'

urlpatterns = [
    path('', views.index, name="index"),
    # path('send/',views.send,name='send'),
]

Blood-Bank-Management-System/bloodbank/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from Paypal import views as pay

urlpatterns = [
                  path('display/', include('display.urls')),
                  path('stock/', include('stock.urls')),
                  path('credits/', include('credits.urls')),
                  path('home/', include('home.urls')),
                  path('pathlab/', include('pathlab.urls')),
                  path('admin/', admin.site.urls),
                  path('find-donor/', include('finddonor.urls')),
                  path('requestblood/', include('requestblood.urls')),
                  path('availability/', include('availability.urls')),
                  path('bloodcamp/', include('bloodcamp.urls')),
                  # path('hospitals/', include('Hospitals.urls')),
                  path('donate/', include('donate.urls')),
                  path('near-you/', include('maps.urls')),
                  re_path(r'^', include('django.contrib.auth.urls')),
                  path('paypal/', include('paypal.standard.ipn.urls')),
                  path('payment-button/', pay.payment_button, name='payment-button'),
                  path('hospitals/', include('Hospitals.urls')),
                  path('requestor/', include('requestor.urls')),

                  ## Rest API :
                  path('rest/', include('RestFramework.urls'), name='rest'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blood-Bank-Management-System/home/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views
# from django.contrib.auth.views import logout_views
from django.contrib.auth import views as auth_views

app_name = 'home'

urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.SignUp, name="signup"),
    path('login/', views.LogIn, name="login"),
    path('logout/', views.user_logout, name="user_logout"),
    path('about/', views.about, name="about"),
    path('profile/', views.profile, name="profile"),
    path('upload/', views.Image_Upload, name="image_upload"),
    path('update_details/', views.Update_Details, name="update_details"),
    path('update_password/', views.Update_Password, name="update_password"),
    path('faq/', views.faq, name="faq"),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),

    path('readmore/',views.readmore,name="readmore"),
    re_path(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name="password_reset"),
    re_path(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    re_path(r'^password_reset/complete/$', auth_views.PasswordResetCompleteView.as_view(),
            name="password_reset_complete"),
    re_path(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),

]

Blood-Bank-Management-System/requestblood/urls.py
from django.urls import path,re_path
from . import views

app_name = 'requestblood'

urlpatterns = [
    path('',views.redi,name='red'),
    path('<req_blood>/', views.index, name='index'),
    re_path(r'^sorry/$', views.sorry, name='sorry'),
    re_path(r'^response/$', views.response, name='response'),
]

Blood-Bank-Management-System/availability/models.py
from django.db import models

Blood_Groups = (
    ('A+', 'A+'),
    ('A-', 'A-'),
    ('B+', 'B+'),
    ('B-', 'B-'),
    ('O+', 'O+'),
    ('O-', 'O-'),
    ('AB+', 'AB+'),
    ('AB-', 'AB-'),
)


# Create your models here.
class BloodAvailability(models.Model):
    threshold = models.IntegerField(default=0)
    quantity = models.IntegerField(default=0)
    blood = models.CharField(max_length=10, choices=Blood_Groups)

    def __str__(self):
        return self.blood;

    def chekingblood(self):
        return '%s, %s, %s' % (self.threshold, self.quantity, self.blood)

Blood-Bank-Management-System/availability/views.py
from django.shortcuts import render
from .models import BloodAvailability



# Create your views here.

def index(request):
    quantity = BloodAvailability.objects.all()
    context = {
        'quantity': quantity
    }
    return render(request, 'availability/index.html', context)



Blood-Bank-Management-System/availability/templates/availability/index.html
{% extends 'home/base.html' %}
{% block head %}
    <title>Blood Availability</title>
{% endblock %}

{% block body %}
    <table style="margin: 80px;width: 100%" class="table table-hover table-bordered">
        <thead>
        <th>S.No.</th>
        <th>Blood Group</th>
        <th>Quantity available</th>
        </thead>
        {% for item in quantity %}

            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.blood }}</td>
                <td>
                    {{ item.quantity }}
                    {% if item.quantity < item.threshold %}
                        <br>
                        <a href="{% url 'requestblood:index' item.blood %}" class="text-center text-danger">*Request a donor</a>
                    {% endif %}
                </td>
            </tr>

        {% endfor %}

    </table>
{% endblock %}

Blood-Bank-Management-System/availability/templates/availability/send.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sending mail</title>
    <p>
        Dear donor, we highly appreciate your generosity.
        Thanks for donating with us!<br>
        <a href="{{ link }}">Home page</a>
        <img src="https://i.pinimg.com/originals/16/9e/fd/169efd8c7bb1f9504335171340dcce0a.jpg" style="width: 400px;height: 400px;">
    </p>

</head>
<body>

</body>
</html>