Blood-Bank-Management-System/bloodbank/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from Paypal import views as pay

urlpatterns = [
                  path('display/', include('display.urls')),
                  path('stock/', include('stock.urls')),
                  path('credits/', include('credits.urls')),
                  path('home/', include('home.urls')),
                  path('pathlab/', include('pathlab.urls')),
                  path('admin/', admin.site.urls),
                  path('find-donor/', include('finddonor.urls')),
                  path('requestblood/', include('requestblood.urls')),
                  path('availability/', include('availability.urls')),
                  path('bloodcamp/', include('bloodcamp.urls')),
                  # path('hospitals/', include('Hospitals.urls')),
                  path('donate/', include('donate.urls')),
                  path('near-you/', include('maps.urls')),
                  re_path(r'^', include('django.contrib.auth.urls')),
                  path('paypal/', include('paypal.standard.ipn.urls')),
                  path('payment-button/', pay.payment_button, name='payment-button'),
                  path('hospitals/', include('Hospitals.urls')),
                  path('requestor/', include('requestor.urls')),

                  ## Rest API :
                  path('rest/', include('RestFramework.urls'), name='rest'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blood-Bank-Management-System/credits/urls.py
from django.urls import path,re_path
from . import views

app_name = 'credits'

urlpatterns = [
    path('',views.index,name = 'index'),
    path('insert/',views.insert,name = 'insert'),
    path('history/',views.history,name = 'history')
]

Blood-Bank-Management-System/finddonor/urls.py
from django.urls import path, re_path
from . import views

app_name = 'finddonor'

urlpatterns = [
    path('', views.index, name='index'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
]

Blood-Bank-Management-System/home/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views
# from django.contrib.auth.views import logout_views
from django.contrib.auth import views as auth_views

app_name = 'home'

urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.SignUp, name="signup"),
    path('login/', views.LogIn, name="login"),
    path('logout/', views.user_logout, name="user_logout"),
    path('about/', views.about, name="about"),
    path('profile/', views.profile, name="profile"),
    path('upload/', views.Image_Upload, name="image_upload"),
    path('update_details/', views.Update_Details, name="update_details"),
    path('update_password/', views.Update_Password, name="update_password"),
    path('faq/', views.faq, name="faq"),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),

    path('readmore/',views.readmore,name="readmore"),
    re_path(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name="password_reset"),
    re_path(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    re_path(r'^password_reset/complete/$', auth_views.PasswordResetCompleteView.as_view(),
            name="password_reset_complete"),
    re_path(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),

]

Blood-Bank-Management-System/requestor/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views
# from django.contrib.auth.views import logout_views
from django.contrib.auth import views as auth_views

app_name = 'requestor'

urlpatterns = [
    path('', views.index, name="index"),
    path('login/',views.requestor_Login, name="requestor_Login"),
    path('logout/',views.requestor_logout,name="requestor_logout"),
    path('profile/', views.profile, name="profile"),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),

]

Blood-Bank-Management-System/requestor/models.py
from django.db import models

# Create your models here.
from django import forms
from django.contrib.auth.models import User
import datetime
from home.models import State, City
from django.core.validators import RegexValidator




class New_requestor(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    rig = models.CharField(max_length=30)
    date_of_registration = models.DateTimeField(auto_now_add=True)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    locality = models.CharField(max_length=400)
    landmark = models.CharField(null= True, max_length=200, blank=True)
    phone = models.CharField(max_length=10,
                             validators=[
                                 RegexValidator(
                                     regex='^[1-9]{1}[0-9]{9}$',
                                     message='Enter a valid phone no',
                                     code='invalid_cell'
                                 ),
                             ]

                             )

    def __str__(self):
        return self.user.username

Blood-Bank-Management-System/requestor/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.http import HttpResponse



class requestorForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget = forms.PasswordInput())
    birth = forms.DateField(widget=forms.SelectDateWidget(years = range(1970,2001)))
    class Meta:
        model = User
        fields = ['username','email','password','first_name']

    def clean(self):
        cleaned_data = super(requestorForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        #print("yes")
        if password != confirm_password:
            #print("no")
            #return HttpResponse("password and confirm password didn't match")
            raise forms.ValidationError("password and confirm password didn't match")

    def __init__(self, *args, **kwargs):
        super(requestorForm, self).__init__(*args, **kwargs)

        for key in self.fields:
            self.fields[key].required = True


class landmarkForm(forms.ModelForm):
    class Meta:
        model = New_requestor
        fields = ['landmark','rig','state','city','phone','locality']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'state' in self.data:
            try:
                state_id = int(self.data.get('state'))
                self.fields['city'].queryset = City.objects.filter(state_id=state_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

Blood-Bank-Management-System/requestor/views.py
from django.http import HttpResponse
from .forms import requestorForm,landmarkForm
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, QueryDict
from home.models import *

def load_cities(request):
    # print("sdhksdsknsl")
    try:
        state_id = request.POST.get('state')
        cities = City.objects.filter(state_id=state_id).order_by('name')

    except:
        cities = City.objects.none()


    #print(state_id)

    # print(cities)
    return render(request, 'requestor/dropdown.html', {'cities': cities})

# Create your views here.

def index(request):
    form = requestorForm()
    landmarkform=landmarkForm()
    if request.user.is_authenticated:
        try:
            if request.user.new_requestor:
                return HttpResponseRedirect(reverse("requestor:profile"))

        except:
            return HttpResponseRedirect(reverse("home:profile"))
    if request.method=="POST":
        form = requestorForm(data = request.POST);
        landmarkform=landmarkForm(data = request.POST)

        if form.is_valid() and landmarkform.is_valid():
            user=form.save(commit=False)
            landmark=landmarkform.save()
            user.set_password(user.password)
            user.save()
            user.is_active = False

            return HttpResponse("Your registration has been taken")
        else:
            messages.error(request, 'This Email or Username already exist')

    return render(request,'requestor/signup.html',{'form':form,'landmarkform':landmarkform})


@login_required
def requestor_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home:index'))


def requestor_Login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("requestor:profile"))

    elif request.method=="POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            #print("user")
            if user.is_active:
                #print("active")
                login(request, user)
                if 'next' in request.POST:
                    try:
                         return redirect(request.POST.get('next'))
                    except:
                        print('Next not found')

                return HttpResponseRedirect(reverse("home:index"))
            #print("yes")
            messages.error(request, 'This user does not exist')
            #return HttpResponseRedirect(reverse("home:login"))

        else:
            print("else")
            messages.error(request, 'username or password does not match')


    return render(request,'requestor/login.html',)



@login_required
def profile(request):
    return render(request,'requestor/profile.html',)

Blood-Bank-Management-System/requestor/templates/requestor/dropdown.html
<option value="">---------</option>
{% for city in cities %}
    <option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

Blood-Bank-Management-System/requestor/templates/requestor/profile.html
{#{% extends 'home/base.html' %}#}
{#{% load static %}#}
{##}
{#{% block head %}#}
{#<title>BloodSource | Profile</title>#}
{#<style media="screen">#}
{#  .bodysize {background-color: rgba(145,40,40,0.6);#}
{#    color:white;#}
{#    height : 1400px;#}
{#    width: 600px;#}
{#  }#}
{##}
{#  .avatar {#}
{#    vertical-align: middle;#}
{#    width: 100px;#}
{#    height: 100px;#}
{#    border-radius: 50%;#}
{#}#}
{#</style>#}
{##}
{##}
{##}
{##}
{#{% endblock %}#}
{##}
{##}
{##}
{#{% block body %}#}
{#<br><br><br>#}
{##}
{##}
{#<div class="container bodysize justify-content-left">#}
{#  <div class="row col-12">#}
{#  <table class="table">#}
{#    <tr>#}
{#      <td>#}
{#    {% if user.userprofile.image  %}#}
{##}
{#    <a href="{% url 'home:image_upload' %}"><img width="300px" height="300px" src="{{user.userprofile.image.url}}"></a>#}
{#    {% else %}#}
{#        {% if user.useraddress.gender == "Female" %}#}
{#        <a href="{% url 'home:image_upload' %}" style="color: black"><img src="{% static 'home/images/girlavatar.png' %}" alt="Avatar" class="avatar"></a>#}
{#        {% else %}#}
{#        <a href="{% url 'home:image_upload' %}" style="color: black"><img src="{% static 'home/images/boyavatar.png' %}" alt="Avatar" class="avatar"></a>#}
{#        {% endif %}#}
{#    {% endif %}#}
{##}
{#          <h3>Your Profile</h3>#}
{#  </td>#}
{#  </tr>#}
{#  <br>#}
{#  <tr>#}
{#    <th>Status:</th>#}
{#    <td>#}
{#    {{user.userprofile.status}}#}
{#  </td>#}
{#  </tr>#}
{#  <tr>#}
{#    <td></td>#}
{#    <td><i><a href="{% url 'home:image_upload' %}" style="color: black">Update Status</a></i></td>#}
{#  </tr>#}
{#  <tr>#}
{#    <td></td>#}
{#    <td></td>#}
{#  </tr>#}
{#    <tr>#}
{#    <th>Personal details</th>#}
{#    <td></td>#}
{#  </tr>#}
{#    <tr>#}
{#    <td>Username:</td>#}
{#    <td>{{user.username}}</td>#}
{#    </tr>#}
{#    <tr>#}
{#    <td>Name:</td>#}
{#    <td>{{user.get_full_name}}</td>#}
{#    </tr>#}
{##}
{#    <tr>#}
{#    <td>Email:</td>#}
{#    <td>{{user.email}}</td>#}
{#    </tr>#}
{#    <tr>#}
{#    <td>Phone:</td>#}
{#    <td>{{user.useraddress.phone}}</td>#}
{#    </tr>#}
{#    <tr>#}
{#    <td>State:</td>#}
{#    <td>{{user.useraddress.state}}</td>#}
{#    </tr>#}
{#    <tr>#}
{#    <td>City:</td>#}
{#    <td>{{user.useraddress.city}}</td>#}
{#    </tr>#}
{#    <tr>#}
{#    <td>Birth Date:</td>#}
{#    <td>{{user.useraddress.birth}}</td>#}
{#    </tr>#}
{#    <tr>#}
{#    <td>Gender:</td>#}
{#    <td>{{user.useraddress.gender}}</td>#}
{#    </tr>#}
{#    <tr>#}
{#    <td>Blood Group:</td>#}
{#    <td>{{user.useraddress.blood}}</td>#}
{#    </tr>#}
{#    <tr>#}
{#    <td>Locality:</td>#}
{#    <td>{{user.useraddress.locality}}</td>#}
{#    </tr>#}
{#    <tr>#}
{#    <td>Landmark:</td>#}
{#    <td>{{user.useraddress.landmark}}</td>#}
{#    </tr>#}
{#    <tr>#}
{#    <td>House:</td>#}
{#    <td>{{user.useraddress.house}}</td>#}
{#    </tr>#}
{#    <tr>#}
{#      <td>#}
{#      </td>#}
{#      <br>#}
{#    <td><a href="{% url 'home:update_details' %}" style="color: black">Update Details</a></td>#}
{#    </tr>#}
{#    <br><br>#}
{#    <tr>#}
{#      <tr>#}
{#        <td></td>#}
{#        <td></td>#}
{#      </tr>#}
{#    <th>Credits details</th>#}
{#    <td></td>#}
{#  </tr>#}
{#      <tr>#}
{#      <td>Current Credits:</td>#}
{#      <td>{{user.wallet.credit}}</td>#}
{#      </tr>#}
{#     <tr>#}
{#      <td></td>#}
{#      <td><a href="{% url 'credits:index' %}" style="color: black">Wallet</a></td>#}
{#      </tr>#}
{#      <tr>#}
{#        <td>#}
{#        </td>#}
{#        <br>#}
{#      <td><a href="{% url 'home:update_password' %}" style="color: black">Update Password</a></td>#}
{#      </tr>#}
{##}
{#  </table>#}
{##}
{#</div>#}
{#</div>#}
{##}
{##}
{#{% endblock %}#}

{% extends 'home/base.html' %}
{% load static %}

{% block head %}
<title>BloodSource | Profile</title>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style media="screen">
  .bodysize {background-color: rgba(244,244,244,0.6);
    color:rgba(70,43,43,0.8);
    height : 600px;
    width: 450px;
    z-index:1;
  }

  .avatar {
    vertical-align: middle;
    width: 100px;
    height: 100px;
    border-radius: 50%;
}

{% if user.userprofile.image  %}
.bodysize {background-color: rgba(244,244,244,0.6);
  color:rgba(70,43,43,0.8);
  height :650px;
  width: 450px;
  z-index:1;
}
{% endif %}


</style>




{% endblock %}



{% block body %}
<br><br><br>


<div class="container bodysize justify-content-left">
  <div class="row col-12">
    <div class="offset-3 col-6">



      <img style="margin-left:30px;" src="{% static 'requestor/institute.png' %}" alt="Avatar" class="avatar">


          <p style="color:blue; margin-top:10px ;margin-left:50px;">@{{user.username}}</p>
            </div>

    <div class="col-8">
    <h3>Personal details</h3>
    <p></p>
    <p><i class="fa fa-user fa-fw
       w3-margin-right w3-large w3-text-teal">
     </i>{{user.first_name}}</p>
    <p></p>
    <p><i class="fa fa-envelope fa-fw
       w3-margin-right w3-large w3-text-teal">
     </i>{{user.email}}</p>
    <p></p>
    <p><i class="fa fa-home fa-fw w3-margin-right w3-large w3-text-teal">
    </i>{{user.new_requestor.locality}},
    {{user.new_requestor.city}},{{user.new_requestor.state}}
    </p>

    <p></p>
  <p><i class="fa fa-flag fa-fw
     w3-margin-right w3-large w3-text-teal">
  </i>{{user.useraddress.landmark}}</p>
  </div>

      <!-- <div class="col-8">
    <h3>Credits details</h3>
    <p></p>
    <p><i class="fa fa-inr fa-fw
       w3-margin-right w3-large w3-text-teal">
     </i>{{user.wallet.credit}}</p>


      <p><a href="{% url 'credits:index' %}" style="color: rgba(12,12,178,0.7)">
        <p><i class="fa fa-money-check fa-fw
         w3-margin-right w3-large w3-text-teal">Wallet
       </i></p></a><p>
         </div> -->
</div>
</div>
</div>


{% endblock %}

Blood-Bank-Management-System/requestor/templates/requestor/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Sign Up</title>

    <!-- Icons font CSS-->
    <link href="{% static 'home/signup/vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'home/signup/vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static 'home/signup/vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'home/signup/vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'home/signup/css/main.css' %}" rel="stylesheet" media="all">
    <script type="text/javascript">
        function myfunct() {
            var x = $("#id_password").val();
            var y = $("#id_confirm_password").val();
            //var date2 = document.getElementById("date").value;
            if (x != y) {
                document.getElementById('ide').innerHTML ="Password and confirmed password didn't match";
                return false;
            }
            else {
                return true;
            }
        }
    </script>
    <script type="text/javascript">
        (function () {
            if (window.localStorage) {
                if (!localStorage.getItem('firstLoad')) {
                    localStorage['firstLoad'] = true;
                    window.location.reload();
                }
                else
                    localStorage.removeItem('firstLoad');
            }
        })();
    </script>

</head>

<body>
    <div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
        <div class="wrapper wrapper--w680">
            <div class="card card-4">
                <div class="card-body">
                    <h2 class="title">Registration Form</h2>
                    <p style="color:red" id="ide"></p>
                    {% if messages %}
                        {% for message in messages %}

                                <p style="color:rgb(255,0,0)">* {{ message }}</p>
                                <p style="margin-top:20px"></p>

                        {% endfor %}
                    {% endif %}
                    <form name="fform" action="{% url 'requestor:index' %}" class="form" method="POST" onsubmit="return myfunct()" id = "find" data - cities - url = "{% url 'finddonor:ajax_load_cities' %}">
                      {% csrf_token %}

                      <div class="row row-space">
                          <div class="col-2">
                              <div class="input-group">
                                  <label class="label">Organization name</label>
                                  <p class="input--style-4">{{ form.first_name }}</p>
                              </div>
                          </div>
                          <div class="col-2">
                              <div class="input-group">
                                  <label class="label">Reg. Id</label>
                                  <p class="input--style-4">{{ landmarkform.rig }}</p>
                              </div>
                          </div>
                      </div>


                      <div class="row row-space">
                          <div class="col-2">
                              <div class="input-group">
                                  <label class="label">Username</label>
                                  <p class="input--style-4">{{ form.username }}</p>
                              </div>
                          </div>
                          <div class="col-2">
                              <div class="input-group">
                                  <label class="label">Email</label>
                                  <p class="input--style-4">{{ form.email }}</p>
                              </div>
                          </div>
                      </div>


                      <div class="row row-space">
                          <div class="col-2">
                              <div class="input-group">
                                  <label class="label">State</label>
                                  <p class="input--style-4">{{ landmarkform.state }}</p>
                              </div>
                          </div>
                          <div class="col-2">
                              <div class="input-group">
                                  <label class="label">City</label>
                                  <p class="input--style-4">{{ landmarkform.city }}</p>
                              </div>
                          </div>
                      </div>


                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Locality</label>
                                    <p class="input--style-4">{{ landmarkform.locality }}</p>
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Landmark</label>
                                    <p class="input--style-4">{{ landmarkform.landmark }}</p>
                                </div>
                            </div>
                        </div>

                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Password</label>
                                    <p class="input--style-4">{{ form.password }}</p>
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Confirm Password</label>
                                    <p class="input--style-4">{{ form.confirm_password }}</p>
                                </div>
                            </div>
                        </div>


                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Phone</label>
                                    <p class="input--style-4">{{ landmarkform.phone }}</p>
                                </div>
                            </div>
                        <div class="p-t-15">
                            <button class="btn btn--radius-2 btn--blue" type="submit">Submit</button>
                        </div>
                        <div>
                    </form>
                </div>
            </div>

        </div>
    <a href="{% url 'home:index' %}" class="offset-6"><button class="btn btn--radius-2 btn--green" type="button">Go to home page</button>
</a>
    </div>

    <script src = "https://code.jquery.com/jquery-3.3.1.min.js" ></script>
        {% csrf_token %}
        <script>
            $("#id_state").change(function () {
                var url = $("#find").attr("data-cities-url");  // get the url of the `load_cities` view
                var stateId = $(this).val();  // get the selected country ID from the HTML input

                $.ajax({
                    type: "POST",// initialize an AJAX request
                    url: '/requestor/ajax/load-cities/',                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                    data: {
                        'state': stateId, csrfmiddlewaretoken: '{{ csrf_token }}'     // add the country id to the GET parameters
                    },
                    success: function (data) {   // `data` is the return of the `load_cities` view function
                        $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
                    }
                });

            });
        </script>
    <!-- Jquery JS-->
    <script src="{% static 'home/signup/vendor/jquery/jquery.min.js' %}"></script>
    <!-- Vendor JS-->
    <script src="{% static 'home/signup/vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'home/signup/vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'home/signup/vendor/datepicker/daterangepicker.js' %}"></script>

    <!-- Main JS-->
    <script src="{% static 'home/signup/js/global.js' %}"></script>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->