Blood-Bank-Management-System/bloodbank/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from Paypal import views as pay

urlpatterns = [
                  path('display/', include('display.urls')),
                  path('stock/', include('stock.urls')),
                  path('credits/', include('credits.urls')),
                  path('home/', include('home.urls')),
                  path('pathlab/', include('pathlab.urls')),
                  path('admin/', admin.site.urls),
                  path('find-donor/', include('finddonor.urls')),
                  path('requestblood/', include('requestblood.urls')),
                  path('availability/', include('availability.urls')),
                  path('bloodcamp/', include('bloodcamp.urls')),
                  # path('hospitals/', include('Hospitals.urls')),
                  path('donate/', include('donate.urls')),
                  path('near-you/', include('maps.urls')),
                  re_path(r'^', include('django.contrib.auth.urls')),
                  path('paypal/', include('paypal.standard.ipn.urls')),
                  path('payment-button/', pay.payment_button, name='payment-button'),
                  path('hospitals/', include('Hospitals.urls')),
                  path('requestor/', include('requestor.urls')),

                  ## Rest API :
                  path('rest/', include('RestFramework.urls'), name='rest'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blood-Bank-Management-System/credits/urls.py
from django.urls import path,re_path
from . import views

app_name = 'credits'

urlpatterns = [
    path('',views.index,name = 'index'),
    path('insert/',views.insert,name = 'insert'),
    path('history/',views.history,name = 'history')
]

Blood-Bank-Management-System/finddonor/urls.py
from django.urls import path, re_path
from . import views

app_name = 'finddonor'

urlpatterns = [
    path('', views.index, name='index'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
]

Blood-Bank-Management-System/home/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views
# from django.contrib.auth.views import logout_views
from django.contrib.auth import views as auth_views

app_name = 'home'

urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.SignUp, name="signup"),
    path('login/', views.LogIn, name="login"),
    path('logout/', views.user_logout, name="user_logout"),
    path('about/', views.about, name="about"),
    path('profile/', views.profile, name="profile"),
    path('upload/', views.Image_Upload, name="image_upload"),
    path('update_details/', views.Update_Details, name="update_details"),
    path('update_password/', views.Update_Password, name="update_password"),
    path('faq/', views.faq, name="faq"),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),

    path('readmore/',views.readmore,name="readmore"),
    re_path(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name="password_reset"),
    re_path(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    re_path(r'^password_reset/complete/$', auth_views.PasswordResetCompleteView.as_view(),
            name="password_reset_complete"),
    re_path(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),

]

Blood-Bank-Management-System/home/models.py
from django.core.validators import RegexValidator
from django.db import models
from django import forms
from django.contrib.auth.models import User
import datetime

# Create your models here.

Blood_Groups = (
    ('A+', 'A+'),
    ('A-', 'A-'),
    ('B+', 'B+'),
    ('B-', 'B-'),
    ('O+', 'O+'),
    ('O-', 'O-'),
    ('AB+', 'AB+'),
    ('AB-', 'AB-'),
)

organisation = (
    ('Blood Bank', 'Blood Bank'),
    ('Apollo Hospitals, Greams Road.', 'Apollo Hospitals, Greams Road.'),
    ('Chettinad Health City, Kelambakkam.', 'Chettinad Health City, Kelambakkam.'),
)

Path_labs = (
    ('Chennai', 'Chennai'),
    ('Bangalore', 'Bangalore'),
    ('Patna', 'Patna'),
    ('Mumbai', 'Mumbai'),
    ('Hyderabad', 'Hyderabad'),
    ('Kolkata', 'Kolkata'),
    ('Delhi', 'Delhi'),
    ('Jamshedpur', 'Jamshedpur'),
)

Gender = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Transgender', 'Transgender'),
)

States = (
    ('Andhra Pradesh', 'Andhra Pradesh'),
    ('Arunachal Pradesh', 'Arunachal Pradesh'),
    ('Assam', 'Assam'),
    ('Bihar', 'Bihar'),
    ('Goa', 'Goa'),
    ('Haryana', 'Haryana'),
    ('Himachal Pradesh', 'Himachal Pradesh'),
    ('Jammu and Kashmir', 'Jammu and Kashmir'),
    ('Jharkhand', 'Jharkhand'),
    ('karnataka', 'karnataka'),
    ('Kerala', 'Kerala'),
    ('Madhya Pradesh', 'Madhya Pradesh'),
    ('Maharashtra', 'Maharashtra'),
    ('Manipur', 'Manipur'),
    ('Meghalaya', 'Meghalaya'),
    ('Mizoram', 'Mizoram'),
    ('Nagaland', 'Nagaland'),
    ('Odisha', 'Odisha'),
    ('Punjab', 'Punjab'),
    ('Rajasthan', 'Rajasthan'),
    ('Sikkim', 'Sikkim'),
    ('Tamil Nadu', 'Tamil Nadu'),
    ('Goa', 'Goa'),
    ('Telangana', 'Telangana'),
    ('Tripura', 'Tripura'),
    ('Uttar Pradesh', 'Uttar Pradesh'),
    ('Uttarakhand', 'Uttarakhand'),
    ('West Bengal', 'West Bengal'),

)


class State(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    def checkingstate(self):
        return self.name


class City(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    def checkingcity(self):
        return '%s, %s' % (self.name, self.state.name)



class UserAddress(models.Model):
    useraddressid = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE, max_length=200)
    locality = models.CharField(max_length=400)
    house = models.CharField(max_length=200)
    landmark = models.CharField(null= True, max_length=200, blank=True)
    phone = models.CharField(max_length=10,
                             validators=[
                                 RegexValidator(
                                     regex='^[1-9]{1}[0-9]{9}$',
                                     message='Enter a valid phone no',
                                     code='invalid_cell'
                                 ),
                             ]

                             )
    birth = models.DateField(null = False)
    gender = models.CharField(max_length=15, choices=Gender)
    date = models.DateTimeField(auto_now_add=True)
    blood = models.CharField(max_length=10, choices=Blood_Groups)

    # last_donated = models.ForeignKey(UserHistory, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.user.username

    def checkinguser(self):
        return '%s, %s, %s' % (self.user.username, self.user.email, self.phone)
        #self.user.first_name, self.user.last_name, self.birth, self.phone,
        #self.gender, self.date, self.blood,self.state.name, self.city.name)



class UserProfile(models.Model):
    userprofileid = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # donoraddress = models.OneToOneField(DonorAddress,on_delete = models.CASCADE)
    status = models.CharField(blank=True, max_length=200)
    feedback = models.CharField(blank=True, max_length=1000)
    image = models.ImageField(upload_to="profile_image", blank=True)

    def __str__(self):
        return self.user.username

    def checkinguserprofile(self):
        return '%s, %s' % (self.user.username, self.status)


class UserHistory(models.Model):
    userhistoryid = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    donation_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.user.username

Blood-Bank-Management-System/home/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.http import HttpResponse


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget = forms.PasswordInput())
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password']

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        #print("yes")
        if password != confirm_password:
            #print("no")
            #return HttpResponse("password and confirm password didn't match")
            raise forms.ValidationError("password and confirm password didn't match")


    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        for key in self.fields:
            self.fields[key].required = True


class UserAddressForm(forms.ModelForm):
    birth = forms.DateField(widget=forms.SelectDateWidget(years = range(1970,2001)))
    class Meta:
        model = UserAddress
        exclude = ['user',]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'state' in self.data:
            try:
                state_id = int(self.data.get('state'))
                self.fields['city'].queryset = City.objects.filter(state_id=state_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

class Upload_Image(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image','status']



class UpdateUser(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name']


class UploadAddress(forms.ModelForm):
    class Meta:
        model = UserAddress
        exclude = ['user','blood','gender']

Blood-Bank-Management-System/home/templates/home/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'home:activate' uidb64=uid token=token %}


Thanks for using our website.
{% endautoescape %}

Blood-Bank-Management-System/home/templates/home/account_activation_sent.html
{% extends 'home/base.html' %}

{% block body %}
  <p>Please confirm your email address to complete the registration. </p>
{% endblock %}

Blood-Bank-Management-System/home/templates/home/dropdown.html
<option value="">---------</option>
{% for city in cities %}
    <option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

Blood-Bank-Management-System/home/templates/home/passwordreset_complete.html
{% extends "home/base.html" %}
{% load static %}
{% block head %}
<title>webpage</title>
<style media="screen">
  .bodysize {background-color: rgba(145,40,40,0.6);
    color:white;
    height : 1000px;
    width: 500px;
    margin-top: 60px;
  }
  </style>
  {% endblock %}



{% block body %}
<div class="container bodysize">
<p>Congrates:</p>

</div>

{% endblock %}

Blood-Bank-Management-System/home/templates/home/passwordreset_confirm.html
{% extends "home/base.html" %}
{% load static %}

{% block head %}
<title>webpage</title>
<style media="screen">
  .bodysize {background-color: rgba(145,40,40,0.6);
    color:white;
    height : 500px;
    width: 500px;
    margin-top: 60px;
  }
  </style>
  {% endblock %}



{% block body %}
<div class="container bodysize">
<form class="form" action="{% url 'home:password_reset_complete' %}" method="post">
  <table class="table">
    <tr>
      <td>New Password</td>
      <td><input type="password" name="new_password" required></td>
    </tr>
    <tr>
      <td>Confirm Password</td>
      <td><input type="password" name="confirm_password" required></td>
    </tr>
    <tr>
      <td></td>
      <td><input type="submit" value="Submit" class="btn btn-outline-success"></td>
    </tr>
  </table>
{% csrf_token %}
</form>
</div>

{% endblock %}

Blood-Bank-Management-System/home/templates/home/passwordreset_done.html
{% extends "home/base.html" %}
{% load static %}
{% block head %}
<title>webpage</title>
<style media="screen">
  .bodysize {background-color: rgba(145,40,40,0.6);
    color:white;
    height : 1000px;
    width: 500px;
    margin-top: 60px;
  }
  </style>
  {% endblock %}



{% block body %}
<div class="container bodysize">
<p>Mail has been sent:</p>

</div>

{% endblock %}

Blood-Bank-Management-System/home/templates/home/passwordreset_mail.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to reset your password:

http://{{ domain }}{% url 'home:password_reset_confirm' uidb64=uid token=token %}


Thanks for using our website.
{% endautoescape %}

Blood-Bank-Management-System/home/templates/home/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Sign Up</title>

    <!-- Icons font CSS-->
    <link href="{% static 'home/signup/vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'home/signup/vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static 'home/signup/vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'home/signup/vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'home/signup/css/main.css' %}" rel="stylesheet" media="all">
    <script type="text/javascript">
        function myfunct() {
            var x = $("#id_password").val();
            var y = $("#id_confirm_password").val();
            //var date2 = document.getElementById("date").value;
            if (x != y) {
                document.getElementById('ide').innerHTML ="Password and confirmed password didn't match";
                return false;
            }
            else {
                return true;
            }
        }
    </script>
    <script type="text/javascript">
        (function () {
            if (window.localStorage) {
                if (!localStorage.getItem('firstLoad')) {
                    localStorage['firstLoad'] = true;
                    window.location.reload();
                }
                else
                    localStorage.removeItem('firstLoad');
            }
        })();
    </script>

</head>

<body>
    <div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
        <div class="wrapper wrapper--w680">
            <div class="card card-4">
                <div class="card-body">
                    <h2 class="title">Registration Form</h2>
                    <p style="color:red" id="ide"></p>
                    {% if messages %}
                        {% for message in messages %}

                                <p style="color:rgb(255,0,0)">* {{ message }}</p>
                                <p style="margin-top:20px"></p>

                        {% endfor %}
                    {% endif %}
                    <form name="fform" action="{% url 'home:signup' %}" class="form" method="POST" id="find" onsubmit="return myfunct()" data - cities - url = "{% url 'finddonor:ajax_load_cities' %}" >
                      {% csrf_token %}
                      <div class="row row-space">
                          <div class="col-2">
                              <div class="input-group">
                                  <label class="label">Username</label>
                                  <p class="input--style-4">{{ form.username }}</p>
                              </div>
                          </div>
                          <div class="col-2">
                              <div class="input-group">
                                  <label class="label">Email</label>
                                  <p class="input--style-4">{{ form.email }}</p>
                              </div>
                          </div>
                      </div>
                      <div class="row row-space">
                          <div class="col-2">
                              <div class="input-group">
                                  <label class="label">first name</label>
                                  <p class="input--style-4">{{ form.first_name }}</p>
                              </div>
                          </div>
                          <div class="col-2">
                              <div class="input-group">
                                  <label class="label">last name</label>
                                <p class="input--style-4">{{ form.last_name }}</p>
                              </div>
                          </div>
                      </div>
                      <div class="row row-space">
                          <div class="col-2">
                              <div class="input-group">
                                  <label class="label">Phone</label>
                                  <p class="input--style-4">{{ address.phone }}</p>
                              </div>
                          </div>
                          <div class="col-2">
                              <div class="input-group">
                                  <label class="label">State</label>
                                  <p class="input--style-4">{{ address.state }}</p>
                              </div>
                          </div>
                      </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">City</label>
                                    <p class="input--style-4">{{ address.city }}</p>
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Locality</label>
                                    <p class="input--style-4">{{ address.locality }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Birthday</label>
                                    <div class="input-group-icon">
                                        <p class="input--style-4">{{ address.birth }}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-2">
                              <div class="col-2">
                                  <div class="input-group">
                                      <label class="label">Gender</label>
                                      <div class="input-group-icon">
                                          <p class="input--style-4">{{ address.gender }}</p>
                                      </div>
                                  </div>
                              </div>
                        </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Landmark</label>
                                    <p class="input--style-4">{{ address.landmark }}</p>
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Apartment</label>
                                    <p class="input--style-4">{{ address.house }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Password</label>
                                    <p class="input--style-4">{{ form.password }}</p>
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Confirm Password</label>
                                    <p class="input--style-4">{{ form.confirm_password }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">Blood Group</label>
                                <div class="input-group-icon">
                                    <p class="input--style-4">{{ address.blood }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="p-t-15">
                            <button class="btn btn--radius-2 btn--blue" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    <a href="{% url 'home:index' %}" class="offset-6"><button class="btn btn--radius-2 btn--green" type="button">Go to home page</button>
</a>
    </div>
    <script src = "https://code.jquery.com/jquery-3.3.1.min.js" ></script>
        {% csrf_token %}
        <script>
            $("#id_state").change(function () {
                var url = $("#find").attr("data-cities-url");  // get the url of the `load_cities` view
                var stateId = $(this).val();  // get the selected country ID from the HTML input

                $.ajax({
                    type: "POST",// initialize an AJAX request
                    url: '/home/ajax/load-cities/',                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                    data: {
                        'state': stateId, csrfmiddlewaretoken: '{{ csrf_token }}'     // add the country id to the GET parameters
                    },
                    success: function (data) {   // `data` is the return of the `load_cities` view function
                        $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
                    }
                });

            });
        </script>

    <!-- Jquery JS-->
    <script src="{% static 'home/signup/vendor/jquery/jquery.min.js' %}"></script>
    <!-- Vendor JS-->
    <script src="{% static 'home/signup/vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'home/signup/vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'home/signup/vendor/datepicker/daterangepicker.js' %}"></script>

    <!-- Main JS-->
    <script src="{% static 'home/signup/js/global.js' %}"></script>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->

Blood-Bank-Management-System/home/templates/home/update_details.html
{% extends "home/base.html" %}
{% load static %}
{% block head %}
<title>webpage</title>
<style media="screen">
  .bodysize {background-color: rgba(145,40,40,0.6);
    color:white;
    height : 1000px;
    width: 500px;
    margin-top: 60px;
  }
  </style>
  {% endblock %}



{% block body %}
<div class="container bodysize">
<form class="form" action="{% url 'home:update_details' %}" method="post">
  <table class="table">
    <tr>
      <td>First Name:</td>
      <td>{{userform.first_name}}</td>
    </tr>
    <tr>
      <td>Last Name:</td>
      <td>{{userform.last_name}}</td>
    </tr>
    <tr>
      <td>State:</td>
      <td>{{addressform.state}}</td>
    </tr>
    <tr>
      <td>City:</td>
      <td>{{addressform.city}}</td>
    </tr>
    <tr>
      <td>Locality:</td>
      <td>{{addressform.locality}}</td>
    </tr>
    <tr>
      <td>Land-Mark:</td>
      <td>{{addressform.landmark}}</td>
    </tr>
    <tr>
      <td>House:</td>
      <td>{{addressform.house}}</td>
    </tr>
    <tr>
      <td>Phone:</td>
      <td>{{addressform.phone}}</td>
    </tr>
    <tr>
      <td>Birth:</td>
      <td>{{addressform.birth}}</td>
    </tr>
    <tr>
      <td></td>
      <td><input type="submit" value="Submit" class="btn btn-outline-success"></td>
    </tr>

  </table>
{% csrf_token %}
</form>
</div>




{% endblock %}

Blood-Bank-Management-System/home/templates/home/uploadedpic.html
{% extends "home/base.html" %}
{% load static %}

{% block head %}
<title>webpage</title>
<style media="screen">
  .bodysize {background-color: rgba(145,40,40,0.6);
    color:white;
    height : 500px;
    width: 500px;
    margin-top: 60px;
  }
  </style>
  {% endblock %}



{% block body %}
<div class="container bodysize">
<form class="form" action="{% url 'home:image_upload' %}" method="post" enctype="multipart/form-data">
  <table class="table">
    <tr>
      <td>Photo</td>
      <td>{{image.image}}</td>
    </tr>
    <tr>
      <td>Status</td>
      <td>{{image.status}}</td>
    </tr>
    <tr>
      <td></td>
      <td><input type="submit" value="Submit" class="btn btn-outline-success"></td>
    </tr>
  </table>
{% csrf_token %}
</form>
</div>

{% endblock %}

Blood-Bank-Management-System/home/templates/home/uploadedpic0.html
{% extends "home/base.html" %}
{% load static %}

{% block head %}
<title>webpage</title>
<style media="screen">
  .bodysize {background-color: rgba(145,40,40,0.6);
    color:white;
    height : 500px;
    width: 500px;
    margin-top: 60px;
  }
  </style>
  {% endblock %}



{% block body %}
<div class="container bodysize">
<form class="form" action="{% url 'home:image_upload' %}" method="post" enctype="multipart/form-data">
  <table class="table">
    <tr>
      <td>Photo</td>
      <td>{{image.image}}</td>
    </tr>
    <tr>
      <td>Status</td>
      <td>{{image.status}}</td>
    </tr>
    <tr>
      <td></td>
      <td><input type="submit" value="Submit" class="btn btn-outline-success"></td>
    </tr>
  </table>
{% csrf_token %}
</form>
</div>

{% endblock %}