Blood-Bank-Management-System/bloodbank/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from Paypal import views as pay

urlpatterns = [
                  path('display/', include('display.urls')),
                  path('stock/', include('stock.urls')),
                  path('credits/', include('credits.urls')),
                  path('home/', include('home.urls')),
                  path('pathlab/', include('pathlab.urls')),
                  path('admin/', admin.site.urls),
                  path('find-donor/', include('finddonor.urls')),
                  path('requestblood/', include('requestblood.urls')),
                  path('availability/', include('availability.urls')),
                  path('bloodcamp/', include('bloodcamp.urls')),
                  # path('hospitals/', include('Hospitals.urls')),
                  path('donate/', include('donate.urls')),
                  path('near-you/', include('maps.urls')),
                  re_path(r'^', include('django.contrib.auth.urls')),
                  path('paypal/', include('paypal.standard.ipn.urls')),
                  path('payment-button/', pay.payment_button, name='payment-button'),
                  path('hospitals/', include('Hospitals.urls')),
                  path('requestor/', include('requestor.urls')),

                  ## Rest API :
                  path('rest/', include('RestFramework.urls'), name='rest'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blood-Bank-Management-System/bloodcamp/urls.py
from django.urls import path, re_path
from . import views

app_name = 'bloodcamp'

urlpatterns = [
    path('volunteering/', views.Volunteering, name="volunteering"),
    path('volunteerlist/', views.VolunteerList, name="volunteer_list"),
    path('history/', views.history, name='history'),
    path('', views.camphome, name='camphome'),
    path('upcoming/', views.upcoming, name='upcoming'),
    path('ongoing/', views.ongoing, name='ongoing'),
    path('newdonor/', views.newdonorpage, name='newdonorpage'),
    path('newcamp/', views.newcamppage, name='newcamppage'),

]

Blood-Bank-Management-System/home/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views
# from django.contrib.auth.views import logout_views
from django.contrib.auth import views as auth_views

app_name = 'home'

urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.SignUp, name="signup"),
    path('login/', views.LogIn, name="login"),
    path('logout/', views.user_logout, name="user_logout"),
    path('about/', views.about, name="about"),
    path('profile/', views.profile, name="profile"),
    path('upload/', views.Image_Upload, name="image_upload"),
    path('update_details/', views.Update_Details, name="update_details"),
    path('update_password/', views.Update_Password, name="update_password"),
    path('faq/', views.faq, name="faq"),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),

    path('readmore/',views.readmore,name="readmore"),
    re_path(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name="password_reset"),
    re_path(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    re_path(r'^password_reset/complete/$', auth_views.PasswordResetCompleteView.as_view(),
            name="password_reset_complete"),
    re_path(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),

]

Blood-Bank-Management-System/bloodcamp/models.py
from django.db import models
from datetime import date

# Create your models here.


Blood_Groups = (
    ('A+', 'A-'),
    ('A-', 'A+'),
    ('B+', 'B+'),
    ('B-', 'B-'),
    ('O+', 'O+'),
    ('O-', 'O-'),
    ('AB+', 'AB+'),
    ('AB-', 'AB-'),
)

Path_labs = (
    ('Chennai', 'Chennai'),
    ('Bangalore', 'Bangalore'),
    ('Patna', 'Patna'),
    ('Mumbai', 'Mumbai'),
    ('Hyderabad', 'Hyderabad'),
    ('Kolkata', 'Kolkata'),
    ('Delhi', 'Delhi'),
    ('Jamshedpur', 'Jamshedpur'),
)

Gender = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Transgender', 'Transgender'),
)

States = (
    ('Andhra Pradesh', 'Andhra Pradesh'),
    ('Arunachal Pradesh', 'Arunachal Pradesh'),
    ('Assam', 'Assam'),
    ('Bihar', 'Bihar'),
    ('Goa', 'Goa'),
    ('Haryana', 'Haryana'),
    ('Himachal Pradesh', 'Himachal Pradesh'),
    ('Jammu and Kashmir', 'Jammu and Kashmir'),
    ('Jharkhand', 'Jharkhand'),
    ('karnataka', 'karnataka'),
    ('Kerala', 'Kerala'),
    ('Madhya Pradesh', 'Madhya Pradesh'),
    ('Maharashtra', 'Maharashtra'),
    ('Manipur', 'Manipur'),
    ('Meghalaya', 'Meghalaya'),
    ('Mizoram', 'Mizoram'),
    ('Nagaland', 'Nagaland'),
    ('Odisha', 'Odisha'),
    ('Punjab', 'Punjab'),
    ('Rajasthan', 'Rajasthan'),
    ('Sikkim', 'Sikkim'),
    ('Tamil Nadu', 'Tamil Nadu'),
    ('Goa', 'Goa'),
    ('Telangana', 'Telangana'),
    ('Tripura', 'Tripura'),
    ('Uttar Pradesh', 'Uttar Pradesh'),
    ('Uttarakhand', 'Uttarakhand'),
    ('West Bengal', 'West Bengal'),

)


class BloodCamp(models.Model):
    # campid = models.CharField(blank=False, null=False, max_length=150)
    campid = models.AutoField(primary_key=True)
    startdate = models.DateField(default=date.today)
    enddate = models.DateField(default=date.today)
    location = models.CharField(blank=False, null=False, max_length=150)
    status = models.CharField(default='1', max_length=1)

    def __str__(self):
        return str(self.campid) + " " + self.location


    def checkingbloodcamp(self):
        return self.location

class BloodCampDonor(models.Model):
    firstname = models.CharField(blank=False, null=False, max_length=150)
    lastname = models.CharField(blank=False, null=False, max_length=150)
    email = models.EmailField()
    phone = models.CharField(max_length=11, blank=True)
    gender = models.CharField(max_length=15, choices=Gender)
    date = models.DateField(auto_now=True, auto_now_add=False)
    blood = models.CharField(max_length=10, choices=Blood_Groups, default='B-')
    bloodcamp = models.ForeignKey(BloodCamp, on_delete=models.CASCADE)

    def __str__(self):
        return self.firstname + " " + self.lastname

    def checkingdonor(self):
        return '%s, %s, %s, %s' % (self.firstname,
        self.email, self.phone, self.bloodcamp)


class BloodVolunteer(models.Model):
    name = models.CharField(blank=False, max_length=100)
    nickname = models.CharField(blank=False, max_length=100)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=11, blank=False)
    state = models.CharField(max_length=30, choices=States, default='Andhra Pradesh')
    city = models.CharField(blank=False, null=False, max_length=200, default='Agra')
    locality = models.CharField(blank=False, max_length=400)
    house = models.CharField(blank=False, max_length=200)
    landmark = models.CharField(blank=False, max_length=200)
    gender = models.CharField(max_length=15, choices=Gender)
    date = models.DateTimeField(auto_now_add=True)
    blood = models.CharField(max_length=10, choices=Blood_Groups)
    bloodcamp = models.ForeignKey(BloodCamp, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def checkingvolunteer(self):
        return '%s, %s, %s, %s' % (self.name,
        self.email, self.phone, self.bloodcamp)

Blood-Bank-Management-System/bloodcamp/forms.py
from .models import *
from django import forms


class VolunteerForm(forms.ModelForm):
    class Meta:
        model = BloodVolunteer
        fields = '__all__'


class newcamp(forms.ModelForm):
    class Meta:
        model = BloodCamp
        fields = ('campid', 'startdate', 'enddate', 'location')


class newdonor(forms.ModelForm):
    class Meta:
        model = BloodCampDonor
        fields = ('firstname','lastname','email','phone','gender','blood','bloodcamp')
    def __init__(self, status, *args, **kwargs):
        super(newdonor, self).__init__(*args, **kwargs)
        self.fields['bloodcamp'].queryset = BloodCamp.objects.filter(status=status)

Blood-Bank-Management-System/bloodcamp/views.py
from datetime import date
from django.http import HttpResponseRedirect
from django.core.mail import send_mail
from django.shortcuts import render
from django.urls import reverse
# from django import forms
from bloodcamp.forms import newdonor, newcamp
from . import forms
from .models import *
from .bloodcamps_functions import default_fun
from django.contrib import messages


# Create your views here.

def Volunteering(request):
    volunteerform = forms.VolunteerForm()
    if request.method == "POST":
        volunteerform = forms.VolunteerForm(data=request.POST)
        if volunteerform.is_valid():
            volunteerform.save()

            return HttpResponseRedirect(reverse('home:index'))
    return render(request, 'bloodcamp/volunteerform.html', {'volunteer': volunteerform})


def VolunteerList(request):
    obj = BloodVolunteer.objects.all()
    return render(request, 'bloodcamp/volunteer_list.html', {'volunteer': obj})



def index(request):
    return render(request, 'bloodcamp/index.html')


def camphome(request):
    return render(request, 'bloodcamp/camphome.html')




def history(request):
    default_fun(request)

    camps = BloodCamp.objects.filter(status='1')
    donors = BloodCampDonor.objects.all()

    for camp in camps:
        print(camp.campid)
        if donors:
            for donor in donors:
                if donor.bloodcamp.campid == camp.campid:
                    print(donor.firstname)

    content = {
        'camps': camps,
        'donors': donors,
    }
    return render(request, 'bloodcamp/history.html', context=content)


def ongoing(request):
    default_fun(request)

    camps = BloodCamp.objects.filter(status=2)
    donors = BloodCampDonor.objects.all()

    for camp in camps:
        print(camp.campid)
        if donors:
            for donor in donors:
                if donor.bloodcamp.campid == camp.campid:
                    print(donor.firstname)

    content = {
        'camps': camps,
        'donors': donors,
    }
    return render(request, 'bloodcamp/ongoing.html', context=content)


def upcoming(request):
    default_fun(request)

    camps = BloodCamp.objects.filter(status=3)
    donors = BloodCampDonor.objects.all()

    for camp in camps:
        print(camp.campid)
        if donors:
            for donor in donors:
                if donor.bloodcamp.campid == camp.campid:
                    print(donor.firstname)

    content = {
        'camps': camps,
        'donors': donors,
    }

    return render(request, 'bloodcamp/upcoming.html', context=content)


def newcamppage(request):
    form = newcamp()
    if request.method == 'POST':
        form = newcamp(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return camphome(request)
        else:
            print('form invalid')
    return render(request, 'bloodcamp/newcamp.html', {'form': form})


def newdonorpage(request):
    form1 = newdonor('3',request.POST)
    if request.method == 'POST':
        bdl=BloodCampDonor.objects.values_list('email', flat=True).filter(bloodcamp=request.POST['bloodcamp'])
        bdl=list(bdl)
        if form1.is_valid() and request.POST['email'] not in bdl:
            form1.save(commit=True)
            firstname = form1.cleaned_data['firstname']
            lastname = form1.cleaned_data['lastname']
            phone = form1.cleaned_data['phone']
            blood = form1.cleaned_data['blood']
            email = str(form1.cleaned_data['email'])
            bloodcamp = form1.cleaned_data['bloodcamp']
            startdate = bloodcamp.startdate
            enddate = bloodcamp.enddate
            send_mail(
                'Blood Bank',
                'FirstName:' + str(firstname) + '\n' +
                'Lastname:' + str(lastname) + '\n' +
                'Phone:' + str(phone) + '\n' +
                'Blood:' + str(blood) + '\n' +
                'startdate:' + str(startdate) + '\n' +
                'enddate:' + str(enddate) + '\n' +
                'Visit on these days to donate blood' + '\n' +
                'bloodcamp:' + str(bloodcamp) + '\n' ,
                '29riyajain@gmail.com',
                [email],
                fail_silently=False,
            )

            return camphome(request)
        else:
            messages.error(request, 'This Email already registered')
    return render(request, 'bloodcamp/newdonor.html', {'form1': form1})

Blood-Bank-Management-System/bloodcamp/templates/bloodcamp/camphome.html
{% extends 'home/base.html' %}
{% load static %}
{% block head %}
    <meta charset="utf-8">
    <title>CAMPS</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">
{% endblock %}
{% block body %}
    <header class="w3-container w3-padding" style="background-color:#E2DCDC">
    <div class="w3-center">
    <p style="font-size:70px">BloodCamps</p>
    </div>
    </header>
    <div class="w3-row-padding w3-center w3-margin-top" style="">
    <div class="w3-third">
      <div class="w3-card w3-container" style="min-height:460px">
      <a href="{% url 'bloodcamp:history' %}" style="text-decoration:none"><h3>History</h3><br>
      <img src="{% static "history.jpg" %}" class="w3-margin-bottom w3-text-theme" style="font-size:120px;width:200px;height:200px">
      <p>Details of the past blood camps</p>
      <p>Details of the donors in that camp</p></a>
      </div>
    </div>

    <div class="w3-third">
    <div class="w3-card w3-container" style="min-height:460px">
    <a href="{% url 'bloodcamp:upcoming' %}" style="text-decoration:none"><h3>Upcoming</h3><br>
    <img src="{% static "upcoming.jpg" %}" class=" w3-margin-bottom w3-text-theme" style="font-size:120px;width:200px;height:200px">
    <p>Details of Upcoming Camps</p></a>
    <a href="{% url 'bloodcamp:newdonorpage' %}" style="text-decoration:none"><p>Pre-registration for that camps </p></a>
    </div>
  </div>

  <div class="w3-third">
    <div class="w3-card w3-container" style="min-height:460px">
    <a href="{% url 'bloodcamp:ongoing' %}" style="text-decoration:none"><h3>Ongoing</h3><br>
    <img src="{% static "ongoing.jpg" %}" class="w3-margin-bottom w3-text-theme" style="font-size:120px;width:200px;height:200px">
    <p>Details of the Ongoing Camps</p>
    </a>
    </div>
  </div>
</div>
{% endblock %}

Blood-Bank-Management-System/bloodcamp/templates/bloodcamp/history.html
{% extends 'home/base.html' %}
{% load static %}
{% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>History</title>
    <link rel="stylesheet" type="text/css" href="{% static "camps.css" %}"
  {% endblock %}

{% block body %}
    <a href="{% url 'bloodcamp:camphome' %}" style="text-decoration:none;color:#701B05" ><h2>&#8592Back</h2></a>
    <h1 class="heading">History</h1><br>
    {% if camps %}


    <table class="camps">
      <tr>
        <th>CampID</th>
        <th>StartDate</th>
        <th>EndDate</th>
        <th>location</th>
        <th>Donators</th>
      </tr>
     </table>

        {% for camp in camps %}
    <table class="camps">
        <tr>
        <td>{{ camp.campid }}</td>
        <td>{{ camp.startdate }}</td>
        <td>{{ camp.enddate }}</td>
        <td>{{ camp.location }}</td>
          <td><button id="btn" name="{{ camp.campid }}" onclick="showdetails(this.name)">show details</button></td>
        </tr>
    </table>
        <!--{% if donors %}-->
     <div id="{{ camp.campid }}"  class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">&times;</span>

            <table class="customers">
                    <tr>
                    <th>Firstname</th>
                    <th>Lastname</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Gender</th>
                    <th>Date</th>
                    <th>Blood</th>
                    </tr>
                    {% for donor in donors %}
                    {% if donor.bloodcamp.campid == camp.campid %}
                    <tr>
                    <td>{{donor.firstname}}</td>
                    <td>{{donor.lastname}}</td>
                    <td>{{donor.email}}</td>
                    <td>{{donor.phone}}</td>
                    <td>{{donor.gender}}</td>
                    <td>{{donor.date}}</td>
                    <td>{{donor.blood}}</td>
                    </tr>
                    {% endif %}
                    {% endfor %}
            </table>
  </div>
</div>

      {% endif %}
      {% endfor %}
     </table>
     {% else %}
        <br><br>
        <h2>No History Camps</h2>
    {% endif %}
 <script>
// Get the modal


// Get the <span> element that closes the modal
// var span = document.getElementsByClassName("close")[0];
var modal;
// When the user clicks the button, open the modal
function showdetails(name) {
  modal = document.getElementById(name);
    modal.style.display = "block";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>
  {% endblock %}

Blood-Bank-Management-System/bloodcamp/templates/bloodcamp/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>HOME</title>
  </head>
  <body>
    <h1>/bloodcamps to go to BLOOD CAMPS</h1>
  </body>
</html>

Blood-Bank-Management-System/bloodcamp/templates/bloodcamp/newcamp.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>New Camp</title>
  </head>
  <body>
    <div class="container">
      <h1>Camp Details</h1>
      <form method="POST">
        {{ form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>
    </div>
  </body>
</html>

Blood-Bank-Management-System/bloodcamp/templates/bloodcamp/newdonor.html
{% extends 'home/base.html' %}
{% load static %}

{% block head %}
<script type="text/javascript">
    (function () {
        if (window.localStorage) {
            if (!localStorage.getItem('firstLoad')) {
                localStorage['firstLoad'] = true;
                window.location.reload();
            }
            else
                localStorage.removeItem('firstLoad');
        }
    })();
</script>
    <title>New Donor</title>
  <style media="screen">
    .backbtn {
        background-color: #84224b;
        color: white;
        padding:10px 15px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        opacity: 0.9;
    }

    .backbtn:hover {
        opacity: 1;
    }
    .registerbtn {
        background-color: #36688D;
        color: white;
        padding: 10px 15px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        opacity: 0.9;
    }

    .registerbtn:hover {
        opacity: 1;
    }
    form {
      margin: 0 auto;
      width:500px;
    }
    body{
       /* background-image:url("{% static '68.jpg'%}") */
       background-color:#54678F; 
    }
  </style>

{% endblock %}
{% block body %}
<center><h1 style="color:#B5C1B4">Register as Donor</h1></center>
<form class="jumbotron" action="" method="post">
    {% if messages %}
      {% for message in messages %}
            <p style="color:rgb(255,102,123)">* {{ message }}</p>
      {% endfor %}
    {% endif %}

      <p>First Name&ensp;&ensp;: {{form1.firstname}}</p>


      <p>Last Name&ensp;&ensp;: {{form1.lastname}}</p>


      <p>Email &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;: {{form1.email}}</p>


      <p>Phone&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;: {{form1.phone}}</p>


      <p>Gender&ensp;&ensp;&ensp;&ensp;&ensp;: {{form1.gender}}</p>


      <p>Blood &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;: {{form1.blood}}</p>


      <p>Blood Camp&ensp;: {{form1.bloodcamp}}</p>


      <p style="padding-top:20px;"><a href="{% url 'bloodcamp:upcoming' %}"><input type="button" class="backbtn" value="Back"></a>
        &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
        <input type="submit" class="registerbtn" value="Register"></p>

  {% csrf_token %}
</form>


{% endblock %}

Blood-Bank-Management-System/bloodcamp/templates/bloodcamp/ongoing.html
{% extends 'home/base.html' %}
{% load static %}
{% block head %}
    <meta charset="utf-8">
    <title>Upcoming</title>
    <link rel="stylesheet" type="text/css" href="{% static "camps.css" %}"
{% endblock %}
{% block body %}
    <a href="{% url 'bloodcamp:camphome' %}" style="text-decoration:none;color:#701B05" ><h2>&#8592Back</h2></a>
    <h1 class="heading">Ongoing Camps</h1><br>
    {% if camps %}
    <table class="camps">
      <tr>
        <th>CampID</th>
        <th>StartDate</th>
        <th>EndDate</th>
        <th>location</th>
      </tr>
      {% for camp in camps %}
        <tr>
        <td>{{ camp.campid }}</td>
        <td>{{ camp.startdate }}</td>
        <td>{{ camp.enddate }}</td>
        <td>{{ camp.location }}</td>
        </tr>
      {% endfor %}
     </table>
    {% else %}
        <br><br>
        <h2>No Ongoing Camps</h2>
    {% endif %}
{% endblock %}

Blood-Bank-Management-System/bloodcamp/templates/bloodcamp/upcoming.html
{% extends 'home/base.html' %}
{% load static %}
{% block head %}

    <meta charset="utf-8">
    <title>Upcoming</title>
    <link rel="stylesheet" type="text/css" href="{% static "camps.css" %}">
    <style media="screen">
      .preregisterbtn {
          background-color: #F28A30;
          color: white;
          padding: 10px 15px;
          margin: 8px 0;
          border: none;
          cursor: pointer;
          opacity: 0.9;
      }

      .preregisterbtn:hover {
          opacity: 1;
      }
    </style>
{% endblock %}
  {% block body %}
    <a href="{% url 'bloodcamp:camphome' %}" style="text-decoration:none;color:#701B05" ><h2>&#8592Back</h2></a>
    <h1 class="heading">Upcoming camps</h1><br>
    {% if camps %}
    <table class="camps">
      <tr>
        <th>CampID</th>
        <th>StartDate</th>
        <th>EndDate</th>
        <th>location</th>
      </tr>
      {% for camp in camps %}
        <tr>
        <td>{{ camp.campid }}</td>
        <td>{{ camp.startdate }}</td>
        <td>{{ camp.enddate }}</td>
        <td>{{ camp.location }}</td>
        </tr>
      {% endfor %}
     </table>
     <center><a href="{% url 'bloodcamp:newdonorpage' %}"><button type="button" class="preregisterbtn" name="Pre-register">Pre-Register</button></a></center>
    {% else %}
        <br><br>
        <h2>No Upcoming Camps</h2>
    {% endif %}
{% endblock %}

Blood-Bank-Management-System/bloodcamp/templates/bloodcamp/volunteer_list.html
{% extends 'home/base.html' %}
{% load static %}

{% block head %}
  <style media="screen">
    {#.table{color:white;#}
      margin-top:150px;
      width:50%;


    }
  </style>

{% endblock %}

{% block body %}

    <table class="table">
      {% if volunteer %}
      <tr>
        <th>Name</th><th>Blood Group</th><th>Camp</th><th>Joining Date</th>
      </tr>
      {% for volunteer in volunteer %}
      <tr>
        <td>{{volunteer.name}}</td><td>{{volunteer.blood}}</td><td>{{volunteer.bloodcamp}}</td>
        <td>{{volunteer.date}}</td>
      </tr>
      {% endfor %}
      {% else %}
      <tr>

        <th>There is no volunteer right now</td>
      </tr>
      <tr>

        <td></td>
      </tr>
      {% endif %}

    </table>

<div style="height:150px;"></div>

{% endblock %}

Blood-Bank-Management-System/bloodcamp/templates/bloodcamp/volunteerform.html
{% extends 'home/base.html' %}
{% load static %}

{% block head %}
  <style>

      .box {
          width: 580px;
          height: 670px;
          background: white;
              box-shadow: 0px 3px 20px black;
          font-size: 7px;

      }



      .table123 {
             font-family:  sans-serif;
             border-collapse: collapse;
             width: 100%;
          font-size: 150%;
      }

        .table123 td, .table123 th {

            padding: 8px;
            font-size: 150%;
            }

        .table123 tr:nth-child(even){background-color: #f2f2f2;}

        .table123 tr:hover {background-color: #ddd;}

        .table123 th {
             border: 1px solid #ddd;
            padding: 25px;
            {#font-size: 150%;#}

            text-align: center;
            background-color:#a31846
;
            color: white;
            }


  </style>

{% endblock %}

{% block body %}
 &nbsp
&nbsp
&nbsp
  <center>
   <div class="box" >

        <form    action="" method="post">
         <table class="table123">
             <tr><th colspan="2">VOLUNTEER REGISTRATION</th></tr>
    <tr>

      <td >Name:</td>
        <td> {{volunteer.name}}</td>

    </tr>
               <tr>

      <td >nick Name:</td>
        <td> {{volunteer.nickname}}</td>

    </tr>


    <tr>
      <td>Email:</td>
      <td>{{volunteer.email}}</td>
    </tr>
    <tr>
      <td >State:</td>
      <td>{{volunteer.state}}</td>
    </tr>
    <tr>
      <td >City:</td>
      <td>{{volunteer.city}}</td>
    </tr>
    <tr>
      <td >Locality:</td>
      <td>{{volunteer.locality}}</td>
    </tr>
    <tr>
      <td >Land-Mark:</td>
      <td>{{volunteer.landmark}}</td>
    </tr>
    <tr>
      <td >House:</td>
      <td>{{volunteer.house}}</td>
    </tr>
    <tr>
      <td >Phone:</td>
      <td>{{volunteer.phone}}</td>
    </tr>
    <tr>
      <td >Gender:</td>
      <td>{{volunteer.gender}}</td>
    </tr>
    <tr>
      <td >Blood:</td>
      <td>{{volunteer.blood}}</td>
    </tr>
    <tr>
      <td >Blood Camp:</td>
      <td>{{volunteer.bloodcamp}}</td>
    </tr>
    <tr style="color: white">

        <td colspan="2"   ><center><input type="submit" value="Submit" class="btn btn-outline-success"  ></center></td>
    </tr>
  </table>
  {% csrf_token %}

  </form>
   </td>
        </tr>
    </div>s
</center>
{% endblock %}